// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC054u7UoGzDZkIgK8pV6alDmqpUf5YuJg',
    appId: '1:435502718618:web:70ca6ecfc03c9763090923',
    messagingSenderId: '435502718618',
    projectId: 'vervestride-app',
    authDomain: 'vervestride-app.firebaseapp.com',
    storageBucket: 'vervestride-app.firebasestorage.app',
    measurementId: 'G-60BHKBBHVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOx87nQh071wpjVKo5iIR1iovsCr9x1iY',
    appId: '1:435502718618:android:dbe137dce705fd43090923',
    messagingSenderId: '435502718618',
    projectId: 'vervestride-app',
    storageBucket: 'vervestride-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuoL6wz_gpte1AL7Z2jyp63QC18IMo5-M',
    appId: '1:435502718618:ios:0a1f3958c2cbfc9d090923',
    messagingSenderId: '435502718618',
    projectId: 'vervestride-app',
    storageBucket: 'vervestride-app.firebasestorage.app',
    androidClientId: '435502718618-5c5lqvdlkoi91vu0e8aca62ndtc29643.apps.googleusercontent.com',
    iosClientId: '435502718618-7rlg24sj66iqiubf1o5oao9cjjsmbd20.apps.googleusercontent.com',
    iosBundleId: 'com.vervestride.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuoL6wz_gpte1AL7Z2jyp63QC18IMo5-M',
    appId: '1:435502718618:ios:8bfdcebf7cd2d50a090923',
    messagingSenderId: '435502718618',
    projectId: 'vervestride-app',
    storageBucket: 'vervestride-app.firebasestorage.app',
    androidClientId: '435502718618-5c5lqvdlkoi91vu0e8aca62ndtc29643.apps.googleusercontent.com',
    iosClientId: '435502718618-nrrerqatgmnfabcf457157hkuf2vcojj.apps.googleusercontent.com',
    iosBundleId: 'com.example.theapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC054u7UoGzDZkIgK8pV6alDmqpUf5YuJg',
    appId: '1:435502718618:web:7f903e4b51ca4379090923',
    messagingSenderId: '435502718618',
    projectId: 'vervestride-app',
    authDomain: 'vervestride-app.firebaseapp.com',
    storageBucket: 'vervestride-app.firebasestorage.app',
    measurementId: 'G-PCT1FPHNM2',
  );

}